// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations should bypass a transaction pooler when DIRECT_URL is set.
    // Local development remains compatible with DATABASE_URL only.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"]!,
  },
});
