import type { HomeData } from './types';

export const homeMockData: HomeData = {
  brand: {
    name: '',
    monogram: 'R',
    address: '',
    primaryColor: '#d64d08',
    whatsapp: '',
    whatsappDisplayName: '',
    whatsappDefaultMessage: '',
    instagram: '',
    facebook: '',
    tiktok: '',
    youtube: '',
  },
  hero: {
    title: '',
    highlight: '',
    description: '',
    image: '',
  },
  banners: [],
  categories: [],
  products: [],
  deliveryTime: '',
  minimumOrder: 0,
  freeDeliveryFrom: 0,
  acceptsDelivery: true,
  acceptsPickup: true,
  acceptsPix: true,
  acceptsCard: true,
  fontFamily: 'Inter',
  seoTitle: '',
  seoDescription: '',
  isOpen: false,
  about: '',
};
