import { BellRing, Clock3, Heart, Minus, Plus, Search, ShoppingBag, Star, UtensilsCrossed, WalletCards, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { digitalMenuMockData } from './data'
import * as S from './DigitalMenu.styles'
import type { CartItem, DigitalMenuProps } from './types'

const brl=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const statusRank={received:0,preparing:1,ready:2}

export function DigitalMenuPage({data=digitalMenuMockData,onCallWaiter,onRequestBill,onSubmitOrder}:DigitalMenuProps){
 const [active,setActive]=useState(data.categories[0]?.id??'');const [query,setQuery]=useState('');const [favorites,setFavorites]=useState<string[]>([]);const [cart,setCart]=useState<CartItem[]>([]);const [drawer,setDrawer]=useState(false);const [notice,setNotice]=useState('')
 const products=useMemo(()=>data.products.filter(product=>{const search=`${product.name} ${product.description}`.toLowerCase().includes(query.toLowerCase());return search&&(active==='featured'||product.categoryId===active)}),[data.products,active,query])
 const featured=products[0]??data.products[0];const recommendations=data.products.filter(x=>x.id!==featured?.id).slice(0,3);const count=cart.reduce((sum,x)=>sum+x.quantity,0);const total=cart.reduce((sum,x)=>sum+x.product.price*x.quantity,0)
 const add=(product=featured)=>{if(!product)return;setCart(items=>{const found=items.find(x=>x.product.id===product.id);return found?items.map(x=>x.product.id===product.id?{...x,quantity:x.quantity+1}:x):[...items,{product,quantity:1}]});setNotice(`${product.name} adicionado`);window.setTimeout(()=>setNotice(''),1500)}
 const quantity=(id:string,change:number)=>setCart(items=>items.map(x=>x.product.id===id?{...x,quantity:x.quantity+change}:x).filter(x=>x.quantity>0))
 const service=(kind:'waiter'|'bill')=>{if(kind==='waiter')onCallWaiter?.();else onRequestBill?.();setNotice(kind==='waiter'?'Garçom chamado com sucesso':'Conta solicitada com sucesso');window.setTimeout(()=>setNotice(''),1800)}
 return <S.Root $primary={data.primaryColor??'#d64d08'}>
  <S.Sidebar><div className="logo">{data.monogram}</div><span className="brand">{data.restaurantName}</span><nav><button className="active"><UtensilsCrossed/>Cardápio</button><button><Heart/>Favoritos</button><button onClick={()=>setDrawer(true)}><ShoppingBag/>Pedidos</button></nav></S.Sidebar>
  <S.Content><S.Top><S.Table><span>▦</span><div><b>Mesa {data.tableNumber}</b><small>● Atendimento no salão</small></div></S.Table><S.Search><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pratos ou ingredientes"/></S.Search><S.TopButton onClick={()=>service('waiter')}><BellRing/>Atendimento</S.TopButton><S.TopButton $primary onClick={()=>setDrawer(true)}><ShoppingBag/>Meu pedido <i>{count}</i></S.TopButton></S.Top><h1>Escolha algo especial</h1>
   <S.Categories>{data.categories.map(category=><S.Category key={category.id} $active={active===category.id} onClick={()=>setActive(category.id)}><img src={category.image} alt=""/><b>{category.name}</b></S.Category>)}</S.Categories>
   {featured&&<S.MainGrid><S.Featured><img src={featured.image} alt={featured.name}/><S.FeaturedCopy><button className="heart" onClick={()=>setFavorites(x=>x.includes(featured.id)?x.filter(id=>id!==featured.id):[...x,featured.id])}><Heart fill={favorites.includes(featured.id)?'currentColor':'none'}/></button><h2>{featured.name}</h2><S.Meta><span><Star className="star"/>{featured.rating}</span><span><Clock3/>{featured.preparationTime}</span></S.Meta><p>{featured.description}</p>{featured.customizable&&<S.Tag>⚙ Personalizável</S.Tag>}<footer><strong>{brl(featured.price)}</strong><button onClick={()=>add()}>Adicionar <Plus/></button></footer></S.FeaturedCopy></S.Featured><ServiceCard status={data.orderStatus} waiter={()=>service('waiter')} bill={()=>service('bill')}/></S.MainGrid>}
   <h3>Recomendados para você</h3><S.Products>{recommendations.map(product=><article key={product.id} onClick={()=>add(product)}><img src={product.image} alt={product.name}/><b>{product.name}</b><strong>{brl(product.price)}</strong></article>)}</S.Products>
  </S.Content><S.OrderBar><b>Pedido da Mesa {data.tableNumber}</b><span>{count} itens</span><strong>{brl(total)}</strong><button onClick={()=>setDrawer(true)}>Revisar pedido ›</button></S.OrderBar>
  {drawer&&<CartDrawer cart={cart} total={total} close={()=>setDrawer(false)} quantity={quantity} submit={()=>{onSubmitOrder?.(cart);setNotice('Pedido enviado para a cozinha');setDrawer(false);window.setTimeout(()=>setNotice(''),1800)}}/>}{notice&&<S.Notice>{notice}</S.Notice>}
 </S.Root>
}

function ServiceCard({status,waiter,bill}:{status:'received'|'preparing'|'ready';waiter:()=>void;bill:()=>void}){const current=statusRank[status];return <S.Service><h2>Seu atendimento</h2><S.Progress>{['Recebido','Em preparo','Pronto para servir'].map((label,index)=><span key={label} style={{display:'contents'}}><S.Step $state={index<current?'done':index===current?'active':'idle'}><i>{index===0?'✓':index===1?'♨':'⌒'}</i><span>{label}</span></S.Step>{index<2&&<S.Line $done={index<current}/>}</span>)}</S.Progress><S.ServiceActions><button onClick={waiter}><BellRing/>Chamar garçom</button><button onClick={bill}><WalletCards/>Pedir a conta</button></S.ServiceActions></S.Service>}

function CartDrawer({cart,total,close,quantity,submit}:{cart:CartItem[];total:number;close:()=>void;quantity:(id:string,n:number)=>void;submit:()=>void}){return <S.Overlay onMouseDown={e=>e.target===e.currentTarget&&close()}><S.Drawer><header><h2>Pedido da mesa</h2><button onClick={close}><X/></button></header>{cart.length===0?<p style={{textAlign:'center',marginTop:50,color:'var(--muted)'}}>Seu pedido ainda está vazio.</p>:cart.map(item=><div className="cart-item" key={item.product.id}><img src={item.product.image} alt=""/><div><b>{item.product.name}</b><span>{brl(item.product.price)}</span><label><span>Observação</span><input placeholder="Ex.: sem cebola" style={{width:'100%',border:'1px solid var(--border)',borderRadius:7,padding:7}}/></label></div><div className="quantity"><button onClick={()=>quantity(item.product.id,-1)}><Minus size={14}/></button><b>{item.quantity}</b><button onClick={()=>quantity(item.product.id,1)}><Plus size={14}/></button></div></div>)}<footer><div><b>Total</b><strong>{brl(total)}</strong></div><button disabled={!cart.length} onClick={submit}>Enviar pedido para a cozinha</button></footer></S.Drawer></S.Overlay>}
