import styled from "styled-components";

export const Root = styled.section`width:min(100%,980px);display:grid;gap:18px;`;
export const Hero = styled.header`
 padding:27px 29px;border:1px solid var(--border);border-radius:18px;background:linear-gradient(135deg,#fff7f1,#fffdfb 65%);box-shadow:0 12px 35px rgba(79,47,23,.06);
 span{display:flex;align-items:center;gap:8px;color:var(--a);font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}span svg{width:17px}h2{margin:12px 0 7px;font-size:clamp(24px,3vw,32px)}p{margin:0;max-width:660px;color:var(--muted);line-height:1.55}`;
export const Guide = styled.div`
 display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;article{overflow:hidden;border:1px solid var(--border);border-radius:14px;background:#fff;transition:box-shadow 180ms ease,border-color 180ms ease}article.open{grid-column:span 2;border-color:color-mix(in srgb,var(--a) 34%,var(--border));box-shadow:0 10px 26px rgba(72,43,22,.07)}article>button{width:100%;min-height:76px;padding:13px 15px;border:0;background:transparent;display:flex;align-items:center;gap:12px;text-align:left;color:#24201d}article>button:hover{background:#fdf9f5}i{width:38px;height:38px;border-radius:12px;color:var(--a);background:#fff0e6;display:grid;place-items:center;flex:0 0 auto}i svg{width:19px}span{min-width:0;display:grid;gap:3px}b{font-size:14px}small{color:var(--muted);font-size:11px}article>button>svg{margin-left:auto;width:18px;color:var(--muted);transition:transform 180ms ease}article.open>button>svg{transform:rotate(180deg)}ol{margin:0;padding:0 23px 19px 65px;display:grid;gap:10px;color:#4b4742;font-size:13px;line-height:1.5}li::marker{color:var(--a);font-weight:800}@media(max-width:650px){grid-template-columns:1fr;article.open{grid-column:auto}ol{padding-left:43px}}`;
export const ReportCard = styled.section`
 padding:25px 28px;border-radius:18px;border:1px solid var(--border);background:#fff;box-shadow:0 12px 35px rgba(79,47,23,.05);.heading{display:flex;align-items:flex-start;gap:13px;margin-bottom:19px}.heading>i{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;color:#fff;background:var(--a)}.heading svg{width:21px}h2{margin:0 0 4px;font-size:19px}p{margin:0;color:var(--muted);font-size:13px;line-height:1.45}form{display:grid;grid-template-columns:minmax(190px,.45fr) minmax(0,1fr);gap:15px}label{display:grid;gap:7px;color:#3a3530;font-size:12px;font-weight:700}select,textarea{width:100%;border:1px solid #ded7cf;border-radius:10px;background:#fcfbf9;color:#25211e;padding:11px 12px;outline:0;transition:border-color 160ms ease,box-shadow 160ms ease}textarea{min-height:92px;resize:vertical;line-height:1.45}select:focus,textarea:focus{border-color:var(--a);background:#fff;box-shadow:0 0 0 4px color-mix(in srgb,var(--a) 10%,transparent)}footer{grid-column:1/-1;min-height:42px;display:flex;align-items:center;gap:12px}footer span{font-size:12px;font-weight:700}.success{color:#18743a}.error{color:#b42318}footer button{margin-left:auto;min-height:42px;padding:0 15px;border:0;border-radius:10px;background:var(--a);color:#fff;display:inline-flex;align-items:center;gap:8px;font-weight:700;box-shadow:0 8px 16px color-mix(in srgb,var(--a) 18%,transparent)}footer button:disabled{opacity:.55;box-shadow:none}footer svg{width:17px}@media(max-width:650px){padding:20px;form{grid-template-columns:1fr}footer{align-items:stretch;flex-direction:column}footer button{margin-left:0;justify-content:center}}`;
export const Tip = styled.p`margin:0;padding:13px 16px;border-radius:12px;color:#635d57;background:#f3f0eb;display:flex;align-items:center;gap:9px;font-size:12px;svg{width:18px;color:var(--a);flex:0 0 auto}`;
