import { Request, Response } from 'express';
import createRestaurantSettingsService from '../services/CreateRestaurantSettingsService.js';

class CreateRestaurantSettingsController {
  async handle(req: Request, res: Response) {
    try {
      const restaurantId = req.user.restaurantId;

      const {
        deliveryFee,
        courierFeePerDelivery,
        minimumOrder,
        pixProvider,
        pixKey,
        legalDocumentType,
        companyDocument,
        companyLegalName,
        companyTradeName,
        companyAddress,
        companyCnae,
        monthlyRevenue,
        ownerFullName,
        ownerCpf,
        ownerBirthDate,
        ownerEmail,
        ownerPhone,
        ownerAddress,
        bankName,
        bankCode,
        bankAccountType,
        bankBranch,
        bankAccount,
        bankHolderDocument,
        cardGateway,
        gatewayMerchantId,
        stripeSecretKey,
        stripeWebhookSecret,
        mercadoPagoAccessToken,
        picpayToken,
        asaasAccessToken,
        pagbankEmail,
        pagbankToken,
        pagbankEnvironment,
        ownerDocumentFileUrl,
        bankProofFileUrl,
        companyContractFileUrl,
        whatsapp,
        instagram,
        facebook,
        restaurantName,
        restaurantLogo,
        restaurantCoverImage,
        restaurantDescription,
        restaurantAddress,
        restaurantAddressNumber,
        restaurantAddressComplement,
        restaurantAddressDistrict,
        restaurantCity,
        restaurantState,
        restaurantZipCode,
        businessHours,
        isOpenForOrders,
        averageDeliveryTime,
        autoAcceptOrders,
        trackingRequiresLogin,
        soundNotifications,
        maxConcurrentOrders,
      } = req.body;

      const settings = await createRestaurantSettingsService.execute({
        restaurantId,
        deliveryFee,
        courierFeePerDelivery,
        minimumOrder,
        pixProvider,
        pixKey,
        legalDocumentType,
        companyDocument,
        companyLegalName,
        companyTradeName,
        companyAddress,
        companyCnae,
        monthlyRevenue,
        ownerFullName,
        ownerCpf,
        ownerBirthDate,
        ownerEmail,
        ownerPhone,
        ownerAddress,
        bankName,
        bankCode,
        bankAccountType,
        bankBranch,
        bankAccount,
        bankHolderDocument,
        cardGateway,
        gatewayMerchantId,
        stripeSecretKey,
        stripeWebhookSecret,
        mercadoPagoAccessToken,
        picpayToken,
        asaasAccessToken,
        pagbankEmail,
        pagbankToken,
        pagbankEnvironment,
        ownerDocumentFileUrl,
        bankProofFileUrl,
        companyContractFileUrl,
        whatsapp,
        instagram,
        facebook,
        restaurantName,
        restaurantLogo,
        restaurantCoverImage,
        restaurantDescription,
        restaurantAddress,
        restaurantAddressNumber,
        restaurantAddressComplement,
        restaurantAddressDistrict,
        restaurantCity,
        restaurantState,
        restaurantZipCode,
        businessHours,
        isOpenForOrders,
        averageDeliveryTime,
        autoAcceptOrders,
        trackingRequiresLogin,
        soundNotifications,
        maxConcurrentOrders,
      });

      return res.status(201).json(settings);
    } catch (error: unknown) {
      return res.status(400).json({
        error:
          error instanceof Error ? error.message : 'Erro ao criar configuracoes do restaurante',
      });
    }
  }
}

export default new CreateRestaurantSettingsController();
