import { Request, Response } from 'express';
import updateRestaurantSettingsService from '../services/UpdateRestaurantSettingsService.js';
import updateDeliveryFeeSettingsService from '../services/UpdateDeliveryFeeSettingsService.js';

class UpdateRestaurantSettingsController {
  async handle(req: Request, res: Response) {
    try {
      const restaurantId = req.user.restaurantId;

      const {
        deliveryFee,
        deliveryFeeMode,
        deliveryFeeRanges,
        courierFeePerDelivery,
        minimumOrder,
        freeShippingMinimum,
        acceptsDelivery,
        acceptsPickup,
        acceptsPix,
        openFinancePixEnabled,
        acceptsCard,
        tableOrderingEnabled,
        waiterCallEnabled,
        billRequestEnabled,
        pixProvider,
        pixKey,
        legalDocumentType,
        companyDocument,
        companyLegalName,
        companyTradeName,
        companyAddress,
        companyCnae,
        monthlyRevenue,
        ownerFullName,
        ownerCpf,
        ownerBirthDate,
        ownerEmail,
        ownerPhone,
        ownerAddress,
        bankName,
        bankCode,
        bankAccountType,
        bankBranch,
        bankAccount,
        bankHolderDocument,
        cardGateway,
        gatewayMerchantId,
        mercadoPagoAccessToken,
        pagarmeSecretKey,
        pagarmePublicKey,
        pagarmeEnvironment,
        picpayToken,
        asaasAccessToken,
        ownerDocumentFileUrl,
        bankProofFileUrl,
        companyContractFileUrl,
        whatsapp,
        whatsappEnabled,
        whatsappDisplayName,
        whatsappDefaultMessage,
        receiveOrdersOnWhatsapp,
        receiveStatusNotifications,
        instagram,
        facebook,
        tiktok,
        youtube,
        primaryColor,
        fontFamily,
        seoTitle,
        seoDescription,
        restaurantName,
        restaurantLogo,
        restaurantCoverImage,
        restaurantDescription,
        restaurantAddress,
        restaurantAddressNumber,
        restaurantAddressComplement,
        restaurantAddressDistrict,
        restaurantCity,
        restaurantState,
        restaurantZipCode,
        businessHours,
        isOpenForOrders,
        averageDeliveryTime,
        autoAcceptOrders,
        trackingRequiresLogin,
        soundNotifications,
        maxConcurrentOrders,
      } = req.body;

      // `whatsapp` é o número comercial canônico do restaurante. ownerPhone é
      // mantido somente por compatibilidade com integrações/KYB antigas e recebe
      // o mesmo valor sempre que o contato comercial é alterado.
      const canonicalCommercialNumber = whatsapp !== undefined ? whatsapp : ownerPhone;

      const settings = await updateRestaurantSettingsService.execute({
        restaurantId,
        deliveryFee,
        courierFeePerDelivery,
        minimumOrder,
        freeShippingMinimum,
        acceptsDelivery,
        acceptsPickup,
        acceptsPix,
        openFinancePixEnabled,
        acceptsCard,
        tableOrderingEnabled,
        waiterCallEnabled,
        billRequestEnabled,
        pixProvider,
        pixKey,
        legalDocumentType,
        companyDocument,
        companyLegalName,
        companyTradeName,
        companyAddress,
        companyCnae,
        monthlyRevenue,
        ownerFullName,
        ownerCpf,
        ownerBirthDate,
        ownerEmail,
        ownerPhone: canonicalCommercialNumber,
        ownerAddress,
        bankName,
        bankCode,
        bankAccountType,
        bankBranch,
        bankAccount,
        bankHolderDocument,
        cardGateway,
        gatewayMerchantId,
        mercadoPagoAccessToken,
        pagarmeSecretKey,
        pagarmePublicKey,
        pagarmeEnvironment,
        picpayToken,
        asaasAccessToken,
        ownerDocumentFileUrl,
        bankProofFileUrl,
        companyContractFileUrl,
        whatsapp: canonicalCommercialNumber,
        whatsappEnabled,
        whatsappDisplayName,
        whatsappDefaultMessage,
        receiveOrdersOnWhatsapp,
        receiveStatusNotifications,
        instagram,
        facebook,
        tiktok,
        youtube,
        primaryColor,
        fontFamily,
        seoTitle,
        seoDescription,
        restaurantName,
        restaurantLogo,
        restaurantCoverImage,
        restaurantDescription,
        restaurantAddress,
        restaurantAddressNumber,
        restaurantAddressComplement,
        restaurantAddressDistrict,
        restaurantCity,
        restaurantState,
        restaurantZipCode,
        businessHours,
        isOpenForOrders,
        averageDeliveryTime,
        autoAcceptOrders,
        trackingRequiresLogin,
        soundNotifications,
        maxConcurrentOrders,
      });

      const deliverySettings = await updateDeliveryFeeSettingsService.execute({
        restaurantId,
        deliveryFeeMode,
        deliveryFeeRanges,
      });

      return res.status(200).json({
        ...settings,
        ...(deliverySettings ?? {}),
      });
    } catch (error: unknown) {
      return res.status(400).json({
        error:
          error instanceof Error ? error.message : 'Erro ao atualizar configuracoes do restaurante',
      });
    }
  }
}

export default new UpdateRestaurantSettingsController();
