import type { AdminSettings, Employee } from "./types";

export const defaultBusinessHours = [
  ["monday", "Segunda-feira"], ["tuesday", "Terça-feira"], ["wednesday", "Quarta-feira"], ["thursday", "Quinta-feira"], ["friday", "Sexta-feira"], ["saturday", "Sábado"], ["sunday", "Domingo"],
].map(([id, label], index) => ({ id, label, enabled: index !== 6, openingTime: "11:00", closingTime: "23:00" }));

export const adminMockSettings: AdminSettings = {
  restaurantName: "",
  companyLegalName: "",
  legalDocumentType: "CNPJ",
  companyDocument: "",
  businessPhone: "",
  businessEmail: "",
  businessZipCode: "",
  businessAddress: "",
  businessAddressNumber: "",
  businessAddressComplement: "",
  businessAddressDistrict: "",
  businessCity: "",
  businessState: "",
  businessHours: defaultBusinessHours,
  isOpenForOrders: true,
  coverImageUrl: "",
  primaryColor: "#d64d08",
  description: "",
  whatsapp: "",
  instagram: "",
  facebook: "",
  minimumOrder: 0,
  deliveryTime: 0,
  autoAcceptOrders: false,
  trackingRequiresLogin: true,
  soundNotifications: true,
  maxConcurrentOrders: 20,
  tableOrderingEnabled: false,
  pixProvider: "MERCADO_PAGO",
  pixKey: "",
  cardGateway: "",
  stripeSecretKey: "",
  stripeSecretKeyConfigured: false,
  stripeWebhookSecret: "",
  stripeWebhookSecretConfigured: false,
  mercadoPagoAccessToken: "",
  mercadoPagoAccessTokenConfigured: false,
  asaasAccessToken: "",
  asaasAccessTokenConfigured: false,
  pagbankEmail: "",
  pagbankToken: "",
  pagbankTokenConfigured: false,
  mainBannerUrl: "",
};

export const adminMockEmployees: Employee[] = [];
