import type { AdminSettings, Employee } from './types';

export const defaultBusinessHours = [
  ['monday', 'Segunda-feira'],
  ['tuesday', 'Terça-feira'],
  ['wednesday', 'Quarta-feira'],
  ['thursday', 'Quinta-feira'],
  ['friday', 'Sexta-feira'],
  ['saturday', 'Sábado'],
  ['sunday', 'Domingo'],
].map(([id, label], index) => ({
  id,
  label,
  enabled: index !== 6,
  openingTime: '11:00',
  closingTime: '23:00',
}));

export const adminMockSettings: AdminSettings = {
  restaurantName: '',
  companyLegalName: '',
  legalDocumentType: 'CNPJ',
  companyDocument: '',
  businessPhone: '',
  businessEmail: '',
  businessZipCode: '',
  businessAddress: '',
  businessAddressNumber: '',
  businessAddressComplement: '',
  businessAddressDistrict: '',
  businessCity: '',
  businessState: '',
  businessHours: defaultBusinessHours,
  businessHoursConfigured: false,
  isOpenForOrders: true,
  coverImageUrl: '',
  primaryColor: '#d64d08',
  description: '',
  whatsapp: '',
  whatsappDisplayName: '',
  whatsappDefaultMessage: '',
  whatsappEnabled: false,
  receiveOrdersOnWhatsapp: false,
  receiveStatusNotifications: false,
  instagram: '',
  facebook: '',
  tiktok: '',
  youtube: '',
  minimumOrder: 0,
  deliveryFee: 0,
  freeShippingMinimum: 0,
  acceptsDelivery: true,
  acceptsPickup: true,
  acceptsPix: true,
  acceptsCard: true,
  deliveryTime: 0,
  autoAcceptOrders: false,
  trackingRequiresLogin: true,
  soundNotifications: true,
  maxConcurrentOrders: 20,
  tableOrderingEnabled: true,
  waiterCallEnabled: true,
  billRequestEnabled: true,
  fontFamily: 'Inter',
  seoTitle: '',
  seoDescription: '',
  pixProvider: 'MERCADO_PAGO',
  pixKey: '',
  cardGateway: '',
  stripeSecretKey: '',
  stripeSecretKeyConfigured: false,
  stripeWebhookSecret: '',
  stripeWebhookSecretConfigured: false,
  mercadoPagoAccessToken: '',
  mercadoPagoAccessTokenConfigured: false,
  asaasAccessToken: '',
  asaasAccessTokenConfigured: false,
  pagbankEmail: '',
  pagbankToken: '',
  pagbankTokenConfigured: false,
  mainBannerUrl: '',
};

export const adminMockEmployees: Employee[] = [];
