import type { AdminSettings, Employee } from './types';

export const defaultBusinessHours = [
  ['monday', 'Segunda-feira'],
  ['tuesday', 'Terça-feira'],
  ['wednesday', 'Quarta-feira'],
  ['thursday', 'Quinta-feira'],
  ['friday', 'Sexta-feira'],
  ['saturday', 'Sábado'],
  ['sunday', 'Domingo'],
].map(([id, label], index) => ({
  id,
  label,
  enabled: index !== 6,
  openingTime: '11:00',
  closingTime: '23:00',
}));

export const adminMockSettings: AdminSettings = {
  restaurantName: '',
  companyLegalName: '',
  legalDocumentType: 'CNPJ',
  companyDocument: '',
  businessPhone: '',
  businessEmail: '',
  businessZipCode: '',
  businessAddress: '',
  businessAddressNumber: '',
  businessAddressComplement: '',
  businessAddressDistrict: '',
  businessCity: '',
  businessState: '',
  businessHours: defaultBusinessHours,
  businessHoursConfigured: false,
  isOpenForOrders: true,
  coverImageUrl: '',
  primaryColor: '#d64d08',
  description: '',
  whatsapp: '',
  whatsappDisplayName: '',
  whatsappDefaultMessage: '',
  whatsappEnabled: false,
  receiveOrdersOnWhatsapp: false,
  receiveStatusNotifications: false,
  instagram: '',
  facebook: '',
  tiktok: '',
  youtube: '',
  minimumOrder: 0,
  deliveryFee: 0,
  freeShippingMinimum: 0,
  acceptsDelivery: true,
  acceptsPickup: true,
  acceptsPix: true,
  openFinancePixEnabled: false,
  acceptsCard: true,
  deliveryTime: 0,
  autoAcceptOrders: false,
  trackingRequiresLogin: true,
  soundNotifications: true,
  maxConcurrentOrders: 20,
  tableOrderingEnabled: true,
  waiterCallEnabled: true,
  billRequestEnabled: true,
  tableAccount: {
    enabled: true,
    requirePrepaymentAboveCents: null,
    prepaymentWindows: [],
    allowCash: true,
    allowCardMachine: true,
    allowOnlinePayment: true,
    allowSplit: true,
    serviceFeeMode: 'DISABLED',
    serviceFeeBasisPoints: 0,
    preventCloseWithOutstandingBalance: true,
    requireEmployeeApprovalForPreparedItemCancellation: true,
    blockNewOrdersOnClosingRequest: true,
    reservationTimeoutMinutes: 10,
    timeZone: 'America/Sao_Paulo',
  },
  fontFamily: 'Inter',
  seoTitle: '',
  seoDescription: '',
  pixProvider: 'MERCADO_PAGO',
  pixKey: '',
  cardGateway: '',
  mercadoPagoAccessToken: '',
  mercadoPagoAccessTokenConfigured: false,
  pagarmeSecretKey: '',
  pagarmePublicKey: '',
  pagarmeEnvironment: 'production',
  pagarmeSecretKeyConfigured: false,
  asaasAccessToken: '',
  asaasAccessTokenConfigured: false,
  promotionalBanners: [],

  deliveryFeeMode: 'FIXED',

  deliveryFeeRanges: [],
};

export const adminMockEmployees: Employee[] = [];
